Product list = ['name of the item', 'relevance', 'price']

Create a function:
    
    to sort, the product list using column passed as an argument
    
    assign page numbers to each product based in itemsPerPage number passed as an argument
    
    get names of the items which are there on a pagenumber passed as an argument
    
    
Arguments:

    df: that was created from the list of lists
    
    n: column number that is used to sort the df
    
    sort: sort ascending or descending (0 or 1)
    
    itemsperPage: no.of items that you want to have in each page
    
    number_of_the_page: number of the page from which you want to see the elements in that page.

In [225]:
import pandas as pd
import math
import numpy as np

In [226]:
x = [["a", 10, 100],
     ["b", 7, 300],
     ["c", 19, 150],
     ["d", 14, 250],
     ["e", 23, 200],
     ["f", 12, 100],
     ["g", 3, 350],
     ["h", 9, 150],
     ["i", 4, 125],
     ["j", 11, 225],
     ["k", 15, 160],
     ["l", 27, 120]]

In [227]:
df = pd.DataFrame(x, columns=['name', 'relevance', 'price'])

In [237]:
def func(df, n, sort, itemsPerPage, number_of_the_page):
    columns = df.columns.tolist()
    column_name = columns[n-1]
    if sort == 0:
        df = df.sort_values(column_name).reset_index(drop=True)
    elif sort == 1:
        df = df.sort_values(column_name, ascending=False).reset_index(drop=True)

    blocks = list(range(0,len(df),itemsPerPage))
    
 
    page_numbers_nested = []
    i = 1
    for j in range(0,len(blocks)):
        if j+1 == len(blocks):
            page_numbers_nested.append([i]*(len(df)-blocks[j]))
        else:
            page_numbers_nested.append([i]*(blocks[j+1]-blocks[j]))
        i += 1
    
    page_numbers = []
    for page in page_numbers_nested:
        for pageno in page:
            page_numbers.append(pageno)
            
    df['page'] = page_numbers
    
    print("items in page number: " + str(number_of_the_page) + '\n', df[df.page == number_of_the_page].name.tolist())
    
    return df

In [238]:
func(df, 2, 1, 2, 2)

items in page number: 2
 ['c', 'k']

   name  relevance  price  page
0     l         27    120     1
1     e         23    200     1
2     c         19    150     2
3     k         15    160     2
4     d         14    250     3
5     f         12    100     3
6     j         11    225     4
7     a         10    100     4
8     h          9    150     5
9     b          7    300     5
10    i          4    125     6
11    g          3    350     6